name: Bug report
description: Signaler un problème reproductible
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Décrivez le bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Listez les étapes
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environnement
      description: OS/Java/Drivers/Cloud
